# Copyright 2022-2026 Axel Huebl
#
# This file is part of ImpactX
#
# License: BSD-3-Clause-LBNL

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "mambaforge-latest"
    # python: "3.11"

sphinx:
  configuration: docs/source/conf.py

conda:
  environment: docs/conda.yml
# python:
#   install:
#   - requirements: docs/requirements.txt

formats:
  - htmlzip
#  - pdf
#  - epub
