/* Copyright 2022-2026 The Regents of the University of California, through Lawrence
 *           Berkeley National Laboratory (subject to receipt of any required
 *           approvals from the U.S. Dept. of Energy). All rights reserved.
 *
 * This file is part of ImpactX.
 *
 * Authors: Axel Huebl
 * License: BSD-3-Clause-LBNL
 */
#ifndef IMPACTX_ELEMENTS_MIXIN_THICK_H
#define IMPACTX_ELEMENTS_MIXIN_THICK_H

#include "particles/ImpactXParticleContainer.H"

#include <AMReX_Extension.H>
#include <AMReX_REAL.H>

#include <stdexcept>


namespace impactx::elements::mixin
{
    /** This is a helper class for lattice elements with finite length
     */
    struct Thick
    {
        static constexpr int DEFAULT_nslice = 1;

        /** A finite-length element
         *
         * @param ds Segment length in m
         * @param nslice number of slices used for the application of space charge,
         *               a positive integer
         */
        Thick (
            amrex::ParticleReal ds,
            int nslice
        )
        : m_ds(ds), m_nslice(nslice)
        {
            if (m_nslice <= 0)
                throw std::invalid_argument("Thick: nslice must be > 0!");
        }

        /** Number of slices used for the application of space charge
         *
         * @return positive integer
         */
        AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE
        int nslice () const
        {
            return m_nslice;
        }

        /** Return the segment length
         *
         * @return value in meters
         */
        AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE
        amrex::ParticleReal ds () const
        {
            return m_ds;
        }

        /** Reverse the element (negate ds)
         *
         * After calling this method, pushing particles through the element
         * reverses the effect of the original element.
         */
        void reverse ()
        {
            m_ds = -m_ds;
        }

        amrex::ParticleReal m_ds; //! segment length in m
        int m_nslice; //! number of slices used for the application of space charge
    };

} // namespace impactx::elements::mixin

#endif // IMPACTX_ELEMENTS_MIXIN_THICK_H
